blank_issues_enabled: false
contact_links:
  - name: Discordサーバー
    url: https://discord.gg/H8dq7wz
    about: 公式Discordサーバーはこちらから
  - name: メール
    url: mailto:midorichan@adm.rspnet.jp
    about: プロジェクトリーダーへのメールはこちらから
